-- MySQL Script generated by MySQL Workbench
-- Sat Mar  9 09:34:28 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema agencia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema agencia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agencia` DEFAULT CHARACTER SET utf8 ;
USE `agencia` ;

-- -----------------------------------------------------
-- Table `agencia`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agencia`.`cidade` (
  `codigo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `estado` VARCHAR(150) NOT NULL,
  `populacao` INT NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencia`.`hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agencia`.`hotel` (
  `codigo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `endereco` VARCHAR(150) NOT NULL,
  `categoria` CHAR(2) NOT NULL,
  `tipo_quarto` CHAR(2) NOT NULL,
  `num_quarto` INT NOT NULL,
  `valor_quarto` DOUBLE(9,2) NOT NULL,
  `cidade_codigo` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_hotel_cidade1_idx` (`cidade_codigo` ASC),
  CONSTRAINT `fk_hotel_cidade1`
    FOREIGN KEY (`cidade_codigo`)
    REFERENCES `agencia`.`cidade` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencia`.`restaurante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agencia`.`restaurante` (
  `codigo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `hotel_codigo` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_restaurante_hotel_idx` (`hotel_codigo` ASC),
  CONSTRAINT `fk_restaurante_hotel`
    FOREIGN KEY (`hotel_codigo`)
    REFERENCES `agencia`.`hotel` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencia`.`igrejas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agencia`.`igrejas` (
  `codigo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(300) NOT NULL,
  `endereco` VARCHAR(150) NOT NULL,
  `estilo_construcao` CHAR(2) NOT NULL,
  `data_de_abertura` DATE NOT NULL,
  `cidade_codigo` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_igrejas_cidade1_idx` (`cidade_codigo` ASC),
  CONSTRAINT `fk_igrejas_cidade1`
    FOREIGN KEY (`cidade_codigo`)
    REFERENCES `agencia`.`cidade` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencia`.`casa_de_show`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agencia`.`casa_de_show` (
  `codigo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(300) NOT NULL,
  `endereco` VARCHAR(150) NOT NULL,
  `data_de_inicio_show` DATE NOT NULL,
  `data_de_fechamento_show` DATE NOT NULL,
  `cidade_codigo` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_casa_de_show_cidade1_idx` (`cidade_codigo` ASC),
  CONSTRAINT `fk_casa_de_show_cidade1`
    FOREIGN KEY (`cidade_codigo`)
    REFERENCES `agencia`.`cidade` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencia`.`museus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agencia`.`museus` (
  `codigo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(300) NOT NULL,
  `endereco` VARCHAR(150) NOT NULL,
  `data_de_fundacao` DATE NOT NULL,
  `numero_de_salas` INT NOT NULL,
  `cidade_codigo` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_museus_cidade1_idx` (`cidade_codigo` ASC),
  CONSTRAINT `fk_museus_cidade1`
    FOREIGN KEY (`cidade_codigo`)
    REFERENCES `agencia`.`cidade` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencia`.`fundadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agencia`.`fundadores` (
  `codigo` INT NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `data_de_nascimento` DATE NOT NULL,
  `data_de_morte` DATE NULL,
  `nacionalidade` VARCHAR(150) NOT NULL,
  `atividade_prof` VARCHAR(150) NOT NULL,
  `museus_codigo` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_fundadores_museus1_idx` (`museus_codigo` ASC),
  CONSTRAINT `fk_fundadores_museus1`
    FOREIGN KEY (`museus_codigo`)
    REFERENCES `agencia`.`museus` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;